title: Troy Udarbe
description: Software Engineer ğŸ“ Toronto, Canada 
| Iâ€™m a software engineer currently building interactive experiences and web applications for fans of the Toronto Maple Leafs and Toronto Raptors at [MLSE Digital Labs](https://www.mlsedigital.com/). 
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
