title: Troy Udarbe
description: Software Engineer ğŸ“ Toronto, Canada 
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/avatar.jpeg
github:
 is_user_page: false
plugins:
- jekyll-remote-theme
